### ISSUE TITLE
Function: Record in Notion

### ISSUE THREAD

**Issue by takuyakikuchi** [shippio/slack-tech-support-recorder#6]
## Deliverables

Upon submission of the form, a new page will be created in Notion reflecting the contents of the form.

Page Creation Location: 500_Development > Tech Support Log

## Todos

- [x] Acquire third-party API credential => Trial with my Notion account
  - [x] Create an integration(https://developers.notion.com/docs/create-a-notion-integration) 
  - [x] Store API credentials as local environment variables
- [x] Implement a function to add item to Notion
- [ ] Acquire third-party API credential => Shippio

## References

- Third-party API calls: https://api.slack.com/future/apicalls/third-party
- Notion API Get Started: https://developers.notion.com/docs/getting-started
- Notion SDK for Deno: https://deno.land/x/notion_sdk@v1.0.4

## Other notes

- Notion API integration
  - Create an integration (🚨 Admin level access is needed to do this) => API Key created
  - Share a database with your integration
  - Save the database ID
